### PR TITLE
Bugfix/8 crash on failed requests

### LINKED ISSUE #8: Crash when request fails
The backoff and other errors are not handled correctly. The execution will stop instead of skipping the cycle one

### PR DESCRIPTION
**Pull request by FelixSFD**
It seems to run stable now: http://chat.stackoverflow.com/transcript/message/35236872#35236872

Closes #8

### CODE REVIEW

File: src/main/java/org/sobotics/guttenberg/finders/RelatedAnswersFinder.java [hunk 1]
```diff
@@ -85,8 +87,9 @@ public RelatedAnswersFinder(List<Integer> ids) {
 			
 			
         } catch (IOException e) {
-			// TODO Auto-generated catch block
+			System.out.println("Error in RelatedAnswersFinder");
 			e.printStackTrace();
+			return null;
```
Comment (Tunaki) [inline src/main/java/org/sobotics/guttenberg/finders/RelatedAnswersFinder.java]: Same.

**Comment by FelixSFD** [comment]
@Tunaki is it better now?
